### ISSUE TITLE
Timer not working

### ISSUE THREAD

**Issue by Etherel90** [SpegalDev/Diablo-4-World-Boss-Tracker#1]
For some reason the timer does not progress. The only way I can get the countdown to update is by disabling and re-enabling the extension. And then it snapshots the time and stops updating again. I have never once gotten the world boss notification because of this issue.

**Comment by SpegalDev** [comment]
Sorry about that. Sometimes the function that fetches the time glitches and stops, and you have to restart it to get it working again. The next update of the extension I do will have error checking in place to automatically restart the timer if it gets hung-up somehow. I hope to have this update out in the coming days.
