### ISSUE TITLE
Time is completely off

### ISSUE THREAD

**Issue by fdellwing** [SpegalDev/Diablo-4-World-Boss-Tracker#2]
Last Avarice spawn was 06:24 UTC, this tracker shows it for 06:59 UTC. Please correct your formula.

**Comment by fdellwing** [comment]
It is now showing 439min but the real time is 305min.

**Comment by SpegalDev** [comment]
Yeah, we've been working on getting the boss spawn times correct. Every once in a while a bad one slips by. I've updated the upcoming times, hopefully no more bad ones get through! Thank you.

**Comment by fdellwing** [comment]
It's very off again.

**Comment by SpegalDev** [comment]
I pushed an update today to fix this issue, apologies for it taking so long.

**Comment by fdellwing** [comment]
You not gonna like it, but its off by more than a hour again.

**Comment by SpegalDev** [comment]
Yeah, I've been having issues with it lately. I need to go back and re-input all the future spawn times. Something went wrong somewhere and it's just been weird the last few days.

Will update here once I get things fully figured out again.
